### ISSUE TITLE
In a workspace project, node_modules may not appear in the subpackage folder

### ISSUE THREAD

**Issue by alvis** [Xunnamius/webpack-node-module-types#8]
Currently, this plugin is run with an assumption that `node_modules` is located under a package folder. While it's true in most cases, it's not the case if a package is under a workspace in which `node_modules` can be located in the root folder.

In this situation, an error `ENOENT: no such file or directory, scandir` will be thrown since there's no `node_modules` under the package folder.

See
https://github.com/Xunnamius/webpack-node-module-types/blob/5784c2b0a3fde5553dab23c3f580c398875998d3/src/sync.ts#L73

**Comment by Xunnamius** [comment]
Fixed in version `1.1.1`:

```TypeScript
const { determineModuleTypes } = require('webpack-node-module-types/sync');
console.log(determineModuleTypes({ rootMode: "upward" }));
```

See the [README](https://github.com/Xunnamius/webpack-node-module-types#monorepo-support) for more info. Thanks again for the report and, if you get the chance, let me know if it's working for you :)
